version: '3'

services:
  db:
    image: mdillon/postgis
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DATABASE_URL=postgres://postgres:@db/postgres
    command: bash -c "cd ./addressresolver && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db