version: '3'

services:
  db:
    image: mdillon/postgis
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
    command: ./start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db