version: '3'

services:
  db:
    container_name: addressresolver-db
    image: mdillon/postgis
    healthcheck:
      test: exit 0
  web:
    container_name: addressresolver-service
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DATABASE_URL=postgis://postgres:@db/postgres
    command: bash -c "python manage.py collectstatic --noinput && ./start.sh"
    volumes:
      - datavolume:/src/static
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    build: ./nginx/
    volumes:
      - datavolume:/src/static
    links:
      - web
    ports:
      - "8000:8000"
    depends_on:
      - web
volumes:
  datavolume: {}