# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visible', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('address',),
            },
        ),
    ]
